const BeerShop={
  brands:[{name:'Karhu III',single:1.45},{name:'Karjala III',single:1.35},{name:'Koff',single:1.30},{name:'Lapin Kulta',single:1.55},{name:'Olvi III',single:1.25},{name:'Sandels',single:1.60},{name:'Lahden Erikois',single:1.70},{name:'Aura',single:1.40}],
  packages:[],averageHistory:[],
  init(){this.createPackages(); document.getElementById('gameMain').insertAdjacentHTML('beforeend',Game.section('Olutkauppa','beerShopContent',`<p>Hinnat muuttuvat 7 päivän välein.</p><h3>Keskihinta / tölkki</h3><canvas id="averagePriceGraph" width="260" height="80"></canvas><div id="beerShopList"></div>`))},
  createPackages(){this.packages=[];this.brands.forEach(b=>[1,6,12].forEach(cans=>{const d=cans===1?1:cans===6?.88:.80,base=Number((b.single*cans*d).toFixed(2));this.packages.push({name:b.name,size:cans===1?'1 tölkki':cans+'-pack',cans,basePrice:base,currentPrice:base,history:[base]})}));this.averageHistory=[this.averagePrice()]},
  averagePrice(){return this.packages.reduce((a,p)=>a+p.currentPrice/p.cans,0)/this.packages.length},
  newDay(){if((Game.state.day-1)%Game.config.priceChangeIntervalDays===0)this.updatePrices()},
  updatePrices(){this.packages.forEach(p=>{let m=p.cans===1?Game.randFloat(.75,1.45):p.cans===6?Game.randFloat(.72,1.35):Game.randFloat(.70,1.30);if(Math.random()<.12&&p.cans>1)m+=Game.randFloat(.10,.28);p.currentPrice=Math.max(.5,Number((p.basePrice*m).toFixed(2)));p.history.push(p.currentPrice)});this.averageHistory.push(this.averagePrice())},
  buy(i){const p=this.packages[i],s=Game.state;if(s.euros<p.currentPrice)return;s.euros-=p.currentPrice;s.fullCans+=p.cans;Game.update()},
  cheapest(){return Math.min(...this.packages.map(p=>p.currentPrice/p.cans))},
  graph(id,values){const c=document.getElementById(id); if(!c)return; const ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#333';ctx.beginPath();ctx.moveTo(0,h-16);ctx.lineTo(w,h-16);ctx.stroke();const min=Math.min(...values),max=Math.max(...values),r=max-min||1;ctx.strokeStyle='#eee';ctx.lineWidth=2;ctx.beginPath();values.forEach((v,i)=>{const x=values.length===1?8:8+i*((w-16)/(values.length-1)),y=8+(1-((v-min)/r))*(h-30);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.stroke();ctx.fillStyle='#aaa';ctx.font='10px monospace';ctx.fillText(min.toFixed(2)+'€',4,h-3);ctx.fillText(max.toFixed(2)+'€',4,11)},
  render(){const list=document.getElementById('beerShopList'); if(!list)return; list.innerHTML=''; this.brands.forEach((b,bi)=>{const matching=this.packages.map((p,i)=>({...p,index:i})).filter(p=>p.name===b.name);let buttons='';matching.forEach(p=>buttons+=`<button onclick="BeerShop.buy(${p.index})" ${Game.state.euros<p.currentPrice?'disabled':''}>${p.size}: ${p.currentPrice.toFixed(2)} €<br>${(p.currentPrice/p.cans).toFixed(2)} €/tlk</button>`);list.insertAdjacentHTML('beforeend',`<div class="beerRow"><div><strong>${b.name}</strong></div><div class="packButtons">${buttons}</div><div><canvas id="beerGraph${bi}" width="250" height="60"></canvas></div></div>`);const hist=[];for(let i=0;i<matching[0].history.length;i++){let sum=0,c=0;matching.forEach(p=>{if(p.history[i]!=null){sum+=p.history[i]/p.cans;c++}});hist.push(sum/c)}this.graph('beerGraph'+bi,hist)});this.graph('averagePriceGraph',this.averageHistory)}
};
Game.register(BeerShop);
