const Kela={
  benefits:{toimeentulotuki:{name:'Toimeentulotuki',amount:56,applied:false,payDay:null,baseDays:30,problems:[]},yleistuki:{name:'Yleistuki',amount:595,applied:false,payDay:null,baseDays:30,problems:[]},asumistuki:{name:'Asumistuki',amount:262,applied:false,payDay:null,baseDays:30,problems:[]}},
  active:null, forms:['Lisäselvitys 17B','Liite K-404','Unohtunut kuitti','Vuokranantajan vahvistus','Tulotietoruutu','Pankkitilin varmistus'], texts:['Hakemuksesta puuttuu outo liite.','Kela pyytää lisäselvitystä asiasta, joka oli jo hakemuksessa.','Järjestelmä haluaa satunnaisia lomakkeita.'],
  init(){Object.values(this.benefits).forEach(b=>b.baseDays=Game.randInt(25,35));document.getElementById('gameMain').insertAdjacentHTML('beforeend',Game.section('Kela','kelaContent',`<div id="kelaList"></div><div id="kelaProblemBox" class="kelaProblem hidden"><h3>Kelan ongelma</h3><p id="kelaProblemText"></p><p id="kelaProblemHint"></p><div id="kelaProblemActions"></div></div>`))},
  apply(type){const b=this.benefits[type];if(b.applied)return;b.applied=true;b.problems=[];b.baseDays=Game.randInt(25,35);b.payDay=Game.state.day+b.baseDays;this.maybeProblem(type,true);Game.update()},
  mult(type){return type==='asumistuki'?.1:1},
  newDay(){for(const type in this.benefits){const b=this.benefits[type];if(b.applied&&b.problems.length===0&&b.payDay-Game.state.day>2&&Math.random()<.12*this.mult(type))this.maybeProblem(type,false);if(b.applied&&b.problems.length===0&&Game.state.day>=b.payDay){Game.state.euros+=b.amount;b.applied=false;b.payDay=null;b.baseDays=Game.randInt(25,35)}}if(!this.active)this.active=this.findNext()},
  maybeProblem(type,fromApply){if(Math.random()>((fromApply?.47:1)*this.mult(type)))return;const forms=Array.from({length:Game.randInt(3,7)},()=>({label:this.forms[Game.randInt(0,this.forms.length-1)],clicked:false}));const needsCall=Math.random()<.45;const p={id:Date.now()+Math.random(),text:this.texts[Game.randInt(0,this.texts.length-1)],forms,needsCall,callDone:!needsCall,callActive:false,callSecondsTotal:needsCall?Game.randInt(2,10):0,callSecondsLeft:0};this.benefits[type].problems.push(p);if(!this.active)this.active={type,id:p.id}},
  current(){if(!this.active)return null;return this.benefits[this.active.type].problems.find(p=>p.id===this.active.id)||null},
  clickForm(i){const p=this.current();if(!p)return;p.forms[i].clicked=true;this.checkSolved();Game.update()},
  call(){const p=this.current();if(!p||p.callDone||p.callActive)return;p.callActive=true;p.callSecondsLeft=p.callSecondsTotal;Game.update()},
  tick(){const p=this.current();if(!p||!p.callActive)return;p.callSecondsLeft--;if(p.callSecondsLeft<=0){p.callActive=false;p.callDone=true;this.checkSolved()}},
  checkSolved(){const p=this.current();if(!p)return;if(p.forms.every(f=>f.clicked)&&p.callDone){const b=this.benefits[this.active.type];b.problems=b.problems.filter(x=>x.id!==p.id);if(b.applied&&b.payDay)b.payDay=Math.max(Game.state.day,b.payDay-1);this.active=this.findNext()}},
  findNext(){for(const type in this.benefits){const p=this.benefits[type].problems[0];if(p)return{type,id:p.id}}return null},
  activeCount(){return Object.values(this.benefits).filter(b=>b.applied).length}, problemCount(){return Object.values(this.benefits).reduce((a,b)=>a+b.problems.length,0)},
  status(type){const b=this.benefits[type];if(!b.applied)return`Ei hakemusta käsittelyssä. Seuraava perusaika: ${b.baseDays} päivää.`;if(b.problems.length)return`Hakemus jumissa. Ongelmat: ${b.problems.length}. Selvitys aikaistaa maksua päivällä.`;return`Hakemus käsittelyssä. Maksupäivä ${b.payDay}. Päiviä jäljellä ${Math.max(b.payDay-Game.state.day,0)}.`},
  render(){const list=document.getElementById('kelaList'); if(!list)return; list.innerHTML=''; Object.entries(this.benefits).forEach(([type,b])=>list.insertAdjacentHTML('beforeend',`<button onclick="Kela.apply('${type}')" ${b.applied?'disabled':''}>Hae ${b.name}</button><p>${b.amount} €, käsittelyaika 25–35 päivää.</p><p>${this.status(type)}</p><hr>`)); const box=document.getElementById('kelaProblemBox'),p=this.current(); if(!p){box.classList.add('hidden');return} box.classList.remove('hidden');document.getElementById('kelaProblemText').textContent=this.benefits[this.active.type].name+': '+p.text;document.getElementById('kelaProblemHint').textContent=`Lomakkeet ${p.forms.filter(f=>f.clicked).length}/${p.forms.length}. Puhelu: ${p.callDone?'valmis':'kesken'}.`;const actions=document.getElementById('kelaProblemActions');actions.innerHTML='';p.forms.forEach((f,i)=>actions.insertAdjacentHTML('beforeend',`<button class="formButton" onclick="Kela.clickForm(${i})" ${f.clicked||p.callActive?'disabled':''}>${f.clicked?'✓ ':''}${f.label}</button>`));if(p.needsCall)actions.insertAdjacentHTML('beforeend',`<br><button onclick="Kela.call()" ${p.callDone||p.callActive?'disabled':''}>${p.callDone?'✓ Puhelu hoidettu':p.callActive?'Puhelu... '+p.callSecondsLeft+' s':'Soita Kelaan ('+p.callSecondsTotal+' s)'}</button>`)}
};
Game.register(Kela);
