const RandomEvents={
  cost:20,
  positives:[['Heräsit ostoskärrystä, joka oli täynnä panttitölkkejä.',()=>{Game.state.emptyCans+=30;return['+30 tyhjää tölkkiä']}],['Sait mystisen hyvityksen pankkitilille.',()=>{Game.state.euros+=50;return['+50.00 €']}],['Luulit meneväsi putkaan, mutta päädyit polttariporukan maskotiksi.',()=>{Game.state.fullCans+=12;return['+12 täyttä tölkkiä']}],['Pultsarikuningas nimitti sinut hovimestariksi.',()=>{Game.state.ryypyt+=80;Game.state.fullCans+=4;return['+80 ryyppyä','+4 täyttä tölkkiä']}]],
  negatives:[['Toriporukka vei taskusta vähän euroja.',()=>{let x=Math.min(Game.state.euros,25);Game.state.euros-=x;return['-'+x.toFixed(2)+' €']}],['Yöllinen sekoilu vei puolet täysistä tölkeistä.',()=>{let old=Game.state.fullCans;Game.state.fullCans=Math.floor(old/2);return['-'+(old-Game.state.fullCans)+' täyttä tölkkiä']}],['Pelikone nielaisi kolikot ja itsekunnioituksen.',()=>{let x=Math.min(Game.state.euros,35);Game.state.euros-=x;Game.changeHangover(8);return['-'+x.toFixed(2)+' €','Krapula +8']}],['Aamulla löytyi vain kuitteja. Ryyppyjä hävisi.',()=>{let x=Math.min(Game.state.ryypyt,50);Game.state.ryypyt-=x;return['-'+x+' ryyppyä']}]],
  init(){document.getElementById('gameMain').insertAdjacentHTML('beforeend',Game.section('Satunnaiset tapahtumat','eventContent',`<p>Hinta on 20 + 35–65 % nykyisistä ryypyistä.</p><p>Hinta: <span id="eventCost">20</span> ryyppyä</p><button id="eventButton" onclick="RandomEvents.trigger()">Käynnistä satunnainen tapahtuma</button><p id="eventLog">Ei tapahtumia vielä.</p>`));this.roll()},
  roll(){this.cost=20+Math.floor(Game.state.ryypyt*Game.randFloat(.35,.65))},
  trigger(){if(Game.state.ryypyt<this.cost)return;const paid=this.cost;Game.state.ryypyt-=paid;const good=Math.random()<.52,list=good?this.positives:this.negatives,ev=list[Game.randInt(0,list.length-1)],changes=ev[1]();Game.state.eventLog=(good?'Hyvä tapahtuma: ':'Huono tapahtuma: ')+ev[0]+' | Maksoit -'+paid+' ryyppyä | '+changes.join(', ');this.roll();Game.update()},
  render(){document.getElementById('eventCost').textContent=this.cost;document.getElementById('eventButton').disabled=Game.state.ryypyt<this.cost;document.getElementById('eventLog').textContent=Game.state.eventLog}
};
Game.register(RandomEvents);
