const Returns={
  returning:false,type:'',total:0,left:0,cans:0,
  init(){document.getElementById('gameMain').insertAdjacentHTML('beforeend',Game.section('Eurojen tienaaminen','moneyContent',`<p>Palautusarvo: <span id="canValue">0.20</span> € / tölkki</p><button id="puulantoriButton" onclick="Returns.start('puulantori')">Palauta Puulantorille — 5 sekuntia, max 5 tölkkiä</button><button id="kilinakoneButton" onclick="Returns.startKilinakone()">Palauta Kilinäkoneeseen — 60 sekuntia, kaikki tölkit</button><p id="returnStatus">Et ole palauttamassa tölkkejä.</p><div class="progressOuter"><div class="progressInner" id="returnProgressBar"></div></div>`))},
  start(type){const s=Game.state;if(this.returning||s.emptyCans<=0)return;this.returning=true;this.type=type;this.cans=type==='puulantori'?Math.min(5,s.emptyCans):s.emptyCans;this.total=type==='puulantori'?5:60;this.left=this.total;s.emptyCans-=this.cans;Game.update()},
  startKilinakone(){Panttikone.start(()=>this.start('kilinakone'))},
  tick(){if(!this.returning)return;this.left--;if(this.left<=0)this.finish()},
  finish(){Game.state.euros+=this.cans*Game.config.canValue;this.returning=false;this.type='';this.total=0;this.left=0;this.cans=0;Game.update()},
  render(){const s=Game.state;document.getElementById('puulantoriButton').disabled=this.returning||s.emptyCans<=0;document.getElementById('kilinakoneButton').disabled=this.returning||s.emptyCans<=0;const rs=document.getElementById('returnStatus'),rb=document.getElementById('returnProgressBar');if(this.returning){const place=this.type==='puulantori'?'Puulantorille':'Kilinäkoneeseen',done=Math.floor(((this.total-this.left)/this.total)*100);rs.textContent=`Palautetaan ${this.cans} tölkkiä ${place}. Aikaa jäljellä: ${this.left} s.`;rb.style.width=done+'%'}else{rs.textContent='Et ole palauttamassa tölkkejä.';rb.style.width='0%'}}
};
const Panttikone={
  events:['Kone sylkee tölkin takaisin naamallesi.','Teinit kuvaavat TikTokiin: äijä vs panttikone.','Eläkeläinen yrittää ohittaa yhdellä mehupullolla.','Humalainen setä alkaa selittää vuoden 1998 finaalia.','Tölkkipussi repeää dramaattisesti.'],
  start(success){let rounds=Game.randInt(4,6),i=0,mistakes=0; const overlay=document.createElement('div'); overlay.className='overlay'; overlay.innerHTML='<div class="overlayBox"><h2>🥫 Panttikoneen raivo</h2><p id="ptInfo"></p><p id="ptText"></p><div id="ptBtns"></div><p>Paina oikeaa nappia nopeasti.</p></div>';document.body.appendChild(overlay); const next=()=>{if(i>=rounds){overlay.remove();success();return} i++;document.getElementById('ptInfo').textContent=`Tilanne ${i}/${rounds} — virheet ${mistakes}/3`;document.getElementById('ptText').textContent=this.events[Game.randInt(0,this.events.length-1)];const opts=['Toimi rauhallisesti','Panikoi','Syytä konetta'].sort(()=>Math.random()-.5);document.getElementById('ptBtns').innerHTML=opts.map(o=>`<button>${o}</button>`).join('');[...document.querySelectorAll('#ptBtns button')].forEach(b=>b.onclick=()=>{if(b.textContent!=='Toimi rauhallisesti')mistakes++; if(mistakes>=3){Game.state.eventLog='Panttikoneen raivo voitti. Menetit muutaman tölkin.';Game.state.emptyCans=Math.max(0,Game.state.emptyCans-Game.randInt(2,8));Game.changeHangover(8);overlay.remove();Game.update();return} next()})}; next()}
};
Game.register(Returns);
